### PR TITLE
Test suite via GitHub actions

### PR DESCRIPTION
**Pull request by rkaldung**
@b1-luettje I changed your workflow a little bit to adjust it to our existing. Please review them before changing your PR https://github.com/znuny/Znuny/pull/25

### CODE REVIEW

**Comment by b1-luettje** [comment]
So i guess `mpm_prefork` is the/your recommended way to run Znuny with apache?

**Comment by rkaldung** [comment]
@b1-luettje Yes, prefork is the recommend mpm for OTRS/Znuny. There is also a check in the support data collector included, see https://github.com/znuny/Znuny/blob/rel-6_0/Kernel/System/SupportDataCollector/Plugin/Webserver/Apache/MPMModel.pm#L49

**Comment by dennykorsukewitz** [comment]
Hi @b1-luettje,

can you please merge (asap) this PullRequest. (into b1-luettje:test_suite_via_github_actions)
After that I can start the review and add my changes.

Thanks and
best regards
Denny

**Comment by dennykorsukewitz** [comment]
Hi @b1-luettje,

wow that was ... super fast 🚀 

Thanks

**Comment by b1-luettje** [comment]
you're welcome (:

**Pull request merged**
